image: alpine/git

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          - git clone --mirror "$BITBUCKET_GIT_HTTP_ORIGIN" repo.git
          - cd repo.git
          # PAT as the *username*, no extra password part
          - git remote add github "https://${GITHUB_PAT}@github.com/xstreck1/smith.git"
          - git push --mirror github