dotnet run -- -C test/sim_params.json
echo "$(tput setaf 7)"
echo "------------------------------------------------------"
echo "- COMPARE FILES --------------------------------------"
echo "------------------------------------------------------"
diff --strip-trailing-cr out/clone_tree.dot test/clone_tree.dot || echo "parent_graph not matching"
diff --strip-trailing-cr out/parent_tree.csv test/parent_tree.csv || echo -e "$(tput setaf 1) \n - parent_tree not matching"
diff --strip-trailing-cr out/populations.csv test/populations.csv || echo -e "$(tput setaf 1) \n - populations not matching"
diff --strip-trailing-cr out/sim_params.json test/sim_params.json || echo -e "$(tput setaf 1) \n - sim_params not matching"
diff --strip-trailing-cr out/subclones.out test/subclones.out || echo -e "$(tput setaf 1) \n - subclones not matching"
diff --strip-trailing-cr out/summary.csv test/summary.csv -I "[0-9][0-9].[0-9]*" || echo -e "$(tput setaf 1) \n - summary not matching" # Ignore time differences  
echo "$(tput setaf 7)"
echo "------------------------------------------------------"
echo "- COMPARISON FINISHED --------------------------------"
echo "------------------------------------------------------"